language: generic

os: osx
osx_image: xcode8.3  # OS X 10.12

branches:
  only:
    - master
    - develop

env:
  global:
    - GETH_VER=geth-darwin-amd64-1.6.4-9c2882b2
    - HYPERG_VER=0.2.1

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip

before_install:
  - brew install python3 qt5 openexr freeimage

  - wget https://gethstore.blob.core.windows.net/builds/${GETH_VER}.tar.gz
  - tar xvf ${GETH_VER}.tar.gz
  - sudo -HE mv ${GETH_VER}/geth /usr/local/bin

  - wget https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v${HYPERG_VER}/hyperg_${HYPERG_VER}_darwin-x64.tar.gz
  - tar xvf hyperg_${HYPERG_VER}_darwin-x64.tar.gz
  - ./hyperg/hyperg &

  - PR_ID=1262
  - PR_APPROVAL_COUNT=$(node scripts/github/get-approvals "${PR_ID}")
  - TEST_MODE=$([ ${PR_APPROVAL_COUNT} >= 2 ] && echo " --runslow" || echo "")

  - sudo -HE pip3 install --upgrade pip setuptools six virtualenv pytest-cov codecov
  - sudo -HE pip3 install -r requirements.txt
  - sudo -HE pip3 install -r requirements-test.txt
  - sudo -HE python3 setup.py develop

script:
  - python3 -m pytest --cov=golem

after_success:
  - python3 -m codecov
  - node scripts/github/set-status ${PR_ID} 'success'

after_error:
  - node scripts/github/set-status ${PR_ID} 'failed'
