language: generic

os: osx
osx_image: xcode8.2  # OS X 10.12

branches:
  only:
    - master
    - develop

cache:
  directories:
    - /usr/local/Cellar
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip

before_install:
  - brew update
  - brew install qt@5.7 openexr xhyve
  - brew install ethereum/ethereum/ethereum ipfs
  - brew install docker-machine docker-machine-driver-xhyve

  - sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  - sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  - docker-machine create --driver xhyve --xhyve-virtio-9p default

  - sudo pip install --upgrade pip setuptools packaging
  - pip install https://github.com/golemfactory/golem/wiki/wheels/sip-4.19-cp27-cp27m-macosx_10_12_x86_64.whl
  - pip install https://github.com/golemfactory/golem/wiki/wheels/PyQt5-5.7.1-cp27-cp27m-macosx_10_12_x86_64.whl
  - sudo pip install -r requirements.txt

  - sudo python setup.py develop

script: pytest tests
