- include_vars:
    file: site_settings.yml
    name: site_settings


- name: add user buildbot worker
  become: yes
  user:
    name: buildbot-worker
    home: /Users/buildbot-worker

# install pythons
- name: install python and deps
  become_user: buildbot-worker
  become: yes
  homebrew:
    name: "{{ item }}"
  with_items:
    - python3
    - openexr
    - freeimage


- name: install buildbot venv
  pip:
    executable: pip3
    name: virtualenv


- name: create buildbot venv
  become_user: buildbot-worker
  become: yes
  command: /usr/local/bin/python3 -m venv /Users/buildbot-worker/.venv
  args:
    creates: /Users/buildbot-worker/.venv

- name: install buildbot and its requirements
  become_user: buildbot-worker
  become: yes
  command: /Users/buildbot-worker/.venv/bin/pip3 install buildbot-worker
  args:
    creates: /Users/buildbot-worker/.venv/bin/buildbot-worker


# # TODO: master address will not be updated once configuration is generated
- name: initialized workspace for the worker
  become_user: buildbot-worker
  become: yes
  command:
    /Users/buildbot-worker/.venv/bin/buildbot-worker create-worker
      /Users/buildbot-worker/worker
      {{worker_master_hostname}}
      {{worker_name}}
      {{site_settings.worker_pass}}
    creates=/Users/buildbot-worker/worker/


- name: copy the launchdaemon file
  become: yes
  copy:
    src: network.golem.buildbot-worker.plist
    dest: /Library/LaunchDaemons/network.golem.buildbot-worker.plist
  notify: load buildbot worker service
