- name: create the BuildResources directory
  win_file:
    path: 'C:\BuildResources'
    state: directory


# wheel mirrored from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32
- name: download resources for the build tasks
  win_get_url:
    url: 'https://s3.amazonaws.com/golem-buildbot-build-resources/pywin32-221-cp36-cp36m-win_amd64.whl'
    dest: 'C:\BuildResources\pywin32-221-cp36-cp36m-win_amd64.whl'
    force: no


- name: check if hyperg installed
  win_stat:
    path: C:\BuildResources\hyperg
  register: hyperg_exists


- name: download hyperg for the build tasks
  win_get_url:
    url: https://github.com/mfranciszkiewicz/golem-hyperdrive/releases/download/v0.2.3/hyperg_0.2.3_windows-x64.zip
    dest: C:\BuildResources\hyperg_0.2.3_windows-x64.zip
    force: no
  when: not hyperg_exists.stat.exists


- name: unzip hyperg for the build tasks
  win_unzip:
    src: C:\BuildResources\hyperg_0.2.3_windows-x64.zip
    dest: C:\BuildResources
    delete_archive: yes
  when: not hyperg_exists.stat.exists


- name: check if geth installed
  win_stat:
    path: C:\BuildResources\geth-windows-amd64-1.7.2-1db4ecdc
  register: geth_exists


- name: download geth for the build tasks
  win_get_url:
    url: https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.7.2-1db4ecdc.zip
    dest: C:\BuildResources\geth-windows-amd64-1.7.2-1db4ecdc.zip
    force: no
  when: not geth_exists.stat.exists

- name: unzip geth for the build tasks
  win_unzip:
    src: C:\BuildResources\geth-windows-amd64-1.7.2-1db4ecdc.zip
    dest: C:\BuildResources
    delete_archive: yes
  when: not geth_exists.stat.exists


- name: check if electron installed
  win_stat:
    path: C:\BuildResources\win-unpacked
  register: electron_exists

- name: download electron for the build tasks
  win_get_url:
    url: https://github.com/golemfactory/golem-electron/releases/download/0.1.4/win-unpacked.zip
    dest: C:\BuildResources\win-unpacked.zip
    force: no
  when: not electron_exists.stat.exists

- name: unzip electron for the build tasks
  win_unzip:
    src: C:\BuildResources\win-unpacked.zip
    dest: C:\BuildResources
    delete_archive: yes
  when: not electron_exists.stat.exists


- name: download docker_toolbox for the build tasks
  win_get_url:
    url: https://download.docker.com/win/stable/DockerToolbox.exe
    dest: C:\BuildResources\DockerToolbox.exe
    force: no
  args:
    creates: C:\BuildResources\DockerToolbox.exe


- name: download vc_redist for the build tasks
  win_get_url:
    url: https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
    dest: C:\BuildResources\vc_redist.x64.exe
    force: no
  args:
    creates: C:\BuildResources\vc_redist.x64.exe
