---
- hosts: tag_role_buildbot_master
  remote_user: ubuntu
  become: yes
  roles:
    - buildbot-master
    - webserver

- hosts: tag_role_buildbot_linux_worker
  remote_user: ubuntu
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts
  roles:
    - buildbot-worker-linux
